# Generated by Django 5.2.7 on 2025-12-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_alter_pokemon_image_alter_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_eng',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
            preserve_default=True,
        ),
    ]
